[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyConDec"
version = "0.0.1"
description = "Module for conditional decorators in Python"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Enrico Skoruppa", email = "enrico.skoruppa@gmail.com" }
]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.optional-dependencies]
numba = ["numba"]

[project.urls]
Homepage = "https://github.com/eskoruppa/pyConDec"
Repository = "https://github.com/eskoruppa/pyConDec"
